telegram:
    bot:
        username: ${BOT_NAME}
        token: ${BOT_TOKEN}
        max_product_quantity: 30

spring:
    datasource:
        url: jdbc:postgresql://${DB_ADDRESS}/${DB_SCHEME}
        driverClassName: org.postgresql.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}