telegram:
    bot:
        username: ${BOT_NAME}
        token: ${BOT_TOKEN}
        max_product_quantity: 30

spring:
    datasource:
        url: jdbc:postgresql://localhost:5430/shopping-list
        driverClassName: org.postgresql.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}