telegram:
    bot:
        username: ${BOT_NAME}
        token: ${BOT_TOKEN}
        max-product-quantity: 30
        languages-file: chatbot/src/main/resources/text-in-languages.json
ai-client:
    url: ${AI_CLIENT_URL}
    response-timeout: PT8S

spring:
    datasource:
        url: jdbc:postgresql://${DB_ADDRESS}/${DB_SCHEME}
        driverClassName: org.postgresql.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}