server:
    port: 9090

ai-client:
    base-url: https://gigachat.devices.sberbank.ru/api/v1/chat/completions
    token-url: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
    client-id: ${SBER_CLIENT_ID}
    client-secret: ${SBER_CLIENT_SECRET}
    scope: GIGACHAT_API_PERS
